package com.isa.isa19.model;
/*
PRAVILNIK
O SPECIJALIZACIJAMA I UŽIM
SPECIJALIZACIJAMA ZDRAVSTVENIH RADNIKA I
ZDRAVSTVENIH SARADNIKA
("Sl. glasnik RS", br. 10/2013)
*/
public enum Specijalizacija {
	INTERNA_MEDICINA,
	INTERNISTICKA_ONKOLOGIJA,
	INFEKTOLOGIJA,
	PEDIJATRIJA,
	NEUROLOGIJA,
	PSIHIJATRIJA,
	DECJA_NEUROLOGIJA,
	DECJA_I_ADOLESCENTNA_PSIHIJATRIJA,
	GINEKOLOGIJA_I_AKUSERSTVO,
	OPSTA_HIRURGIJA,
	ABDOMINALNA_HIRURGIJA,
	VASKULARNA_HIRURGIJA,
	GRUDNA_HIRURGIJA,
	ORTOPEDSKA_HIRURGIJA_I_TRAUMATOLOGIJA,
	DECJA_HIRURGIJA,
	NEUROHIRURGIJA,
	PLASTICNA,_REKONSTRUKTIVNA_I_ESTETSKA_HIRURGIJA,
	MAKSILOFACIJALNA_HIRURGIJA,
	UROLOGIJA,
	KARDIOHIRURGIJA,
	URGENTNA_MEDICINA,
	ANESTEZIOLOGIJA_REANIMATOLOGIJA_I_INTENZIVNA_TERAPIJA,
	OTORINOLARINGOLOGIJA,
	OFTALMOLOGIJA,
	DERMATOVENEROLOGIJA,
	FIZIKALNA_MEDICINA_I_REHABILITACIJA,
	OPSTA_MEDICINA,
	MEDICINA_RADA,
	RADIOLOGIJA,
	RADIJACIONA_ONKOLOGIJA,
	NUKLEARNA_MEDICINA,
	PATOLOGIJA,
	SUDSKA_MEDICINA,
	MEDICINSKA_MIKROBIOLOGIJA,
	KLINICKA_BIOHEMIJA,
	KLINICKA_FARMAKOLOGIJA,
	LABORATORIJSKA_MEDICINA,
	IMUNOLOGIJA,
	HIGIJENA,
	EPIDEMIOLOGIJA,
	SOCIJALNA_MEDICINA,
	SPORTSKA_MEDICINA,
	TRANSFUZIJSKA_MEDICINA,
	VAZDUHOPLOVNA_MEDICINA;
}
