package com.isa.isa19.model;

public enum StatusPregledaOperacije {
	BRZI_PREGLED,
	REZERVISAN_PREGLED,
	ZAKAZAN_PREGLED,
	OTKAZAN_PREGLED,
	IZVRSEN_PREGLED,
	ZAKAZANA_OPERACIJA,
	OTKAZANA_OPERACIJA,
	IZVRSENA_OPERACIJA
}
