package com.isa.isa19.model;

public enum TipDogadjajaKalendar {
	ZAHTEVANIO_ODMOR,
	ODOBRENI_ODMOR,
	ZAHTEVANO_ODSUSTVO,
	ODOBRENEO_ODSUSTVO,
	ZAKAZAN_PREGLED,
	OTKAZAN_PREGLED,
	ZAKAZANA_OPERACIJA,
	OTKAZANA_OPERACIJA

}
